# Generated by Django 3.1.12 on 2025-01-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0004_alter_student_cv_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
