# Generated by Django 5.1.5 on 2025-01-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0005_auto_20250122_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
