# Generated by Django 5.1.5 on 2025-01-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0006_remove_student_cv_remove_student_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
