# Generated by Django 5.1.5 on 2025-01-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0008_examresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
