# Generated by Django 5.1.5 on 2025-01-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0011_cheatinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatinglog',
            name='captured_frame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cheatinglog',
            name='cheat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cheatinglog',
            name='exam',
            field=models.CharField(default='Default Exam', max_length=100),
        ),
        migrations.AddField(
            model_name='cheatinglog',
            name='student',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='cheatinglog',
            name='objects_detected',
            field=models.CharField(max_length=255),
        ),
    ]
