# Generated by Django 5.1.5 on 2025-01-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0012_cheatinglog_captured_frame_cheatinglog_cheat_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatinglog',
            name='student',
        ),
        migrations.AlterField(
            model_name='cheatinglog',
            name='captured_frame',
            field=models.ImageField(upload_to='cheating_frames/'),
        ),
        migrations.AlterField(
            model_name='cheatinglog',
            name='exam',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cheatinglog',
            name='objects_detected',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cheatinglog',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
