# Generated by Django 5.1.5 on 2025-01-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0015_cheatingevent_delete_cheatingincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatingevent',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
