# Generated by Django 5.1.5 on 2025-01-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0016_cheatingevent_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatingevent',
            name='metadata',
        ),
    ]
