# Generated by Django 5.1.5 on 2025-01-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0017_remove_cheatingevent_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingevent',
            name='cheat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='detected_object',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='image',
            field=models.ImageField(upload_to='cheating_events/'),
        ),
    ]
