# Generated by Django 3.1.12 on 2025-01-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0019_exam_delete_examresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='face_encoding',
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='feedback',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='student_photos/'),
        ),
    ]
