# Generated by Django 3.1.12 on 2025-01-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0020_auto_20250126_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
