# Generated by Django 3.1.12 on 2025-01-27 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0021_student_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatingevent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cheatingevent',
            name='student',
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='cheating_images/'),
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='proctoring_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheating_events', to='proctoring.exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(default='Default Exam Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='detected_object',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='proctoring.student'),
        ),
    ]
