# Generated by Django 3.1.12 on 2025-01-27 09:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0025_auto_20250127_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AddField(
            model_name='exam',
            name='correct_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='proctoring.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(default='Default Exam Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
