# Generated by Django 3.1.12 on 2025-01-27 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0026_auto_20250127_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
