# Generated by Django 3.1.12 on 2025-01-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0027_auto_20250127_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ongoing', max_length=50),
        ),
    ]
