# Generated by Django 3.1.12 on 2025-01-27 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proctoring', '0028_exam_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheatingevent',
            old_name='detected_object',
            new_name='event_type',
        ),
        migrations.RemoveField(
            model_name='cheatingevent',
            name='images',
        ),
        migrations.RemoveField(
            model_name='cheatingevent',
            name='proctoring_exam',
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='detected_audio/'),
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='frame_image',
            field=models.ImageField(blank=True, null=True, upload_to='detected_frames/'),
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
