# Generated by Django 3.1.12 on 2025-01-28 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proctoring', '0029_auto_20250127_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatingevent',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='cheatingevent',
            name='cheat_count',
        ),
        migrations.RemoveField(
            model_name='cheatingevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='cheatingevent',
            name='frame_image',
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='audio_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='cheating_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='detected_faces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='detected_objects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='face_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cheatingevent',
            name='head_pose',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
